### ISSUE TITLE
[Android Bootcamp] Pre-work: Todo App - Review my app

### ISSUE THREAD

**Issue by Monte9** [Monte9/TodoApp-Android#3]

**Comment by Monte9** [comment]
My app is complete, please review /cc @codepath @codepathreview

Also can you let me know if I implemented intent correctly? What I did was to check a specific intent data each time in the onCreate method of the sender Activity and take the appropriate action.

**Comment by nesquena** [comment]
Hi Monte,

Looks good, and thanks for submitting your pre-work. We hope you enjoyed working on the project! Unfortunately, due to high demand this round, we are restricting participation in July to those with at least 1 year of experience after graduating with an engineering degree (excluding internships). We hope you are able to participate in a future cohort though! (and glad you were able to do CodePathU for iOS).

In the meantime, there are a lot of resources out there for people interested in learning Android and we’ve done some work to make them more accessible. We [have many online resources for learning Android](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-do-not-live-in-the-bay-area-can-i-take-your-classes-locally-or-remotely) including a long list of [Android resources online](http://guides.codepath.com/android/Beginning-Android-Resources#beginning-android-resources). You can also follow [us on Twitter @codepath](https://twitter.com/codepath) for news of future courses.

Hope to be able to expand our audience for future programs. Thanks for your understanding,
